//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanpingPage.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoShop
    {
        public int InfoID { get; set; }
        public string Title { get; set; }
        public string Img { get; set; }
        public string Description { get; set; }
    }
}
